### ISSUE TITLE
Chef Supermarket does not link to this repository

### ISSUE THREAD

**Issue by rhass-r7** [jsirex/simple-kibana-cookbook#1]
The Chef Supermarket entry `https://supermarket.chef.io/cookbooks/simple-kibana` does not contain links to this repo which made finding it a little difficult.

**Comment by rhass-r7** [comment]
It looks like the latest commit may have fixed this issue, and it just needs to be released.

**Comment by jsirex** [comment]
Will release patch on this monday. Will reopen it and close after new release.

Thank you!
