### ISSUE TITLE
Error executing action 'start'

### ISSUE THREAD

**Issue by joberg02** [jsirex/simple-kibana-cookbook#12]
When running this cookbook as part of a vagrant up provisioning step I am getting the following error:

 ================================================================================
 Error executing action `start` on resource 'runit_service[kibana]'
 ================================================================================
 Mixlib::ShellOut::ShellCommandFailed

---

 Expected process to exit with [0], but received '1'
 ---- Begin output of /sbin/sv start /etc/service/kibana ----
 STDOUT: warning: /etc/service/kibana: unable to open supervise/ok: file does not exist
 STDERR:
 ---- End output of /sbin/sv start /etc/service/kibana ----
 Ran /sbin/sv start /etc/service/kibana returned 1

This will then of course give me a return status of a 1 in my wrapper recipe which we have hooked into Jenkins for a continuous integration build and turn the build red.  If I remove ":start" out of the "action" call in the service_runit.rb file the build will complete successfully and the build goes green and kibana is up and running without any other intervention.

Has anybody else experienced this issue?  Or should I scrap runit and use something else?

Thanks!

**Comment by jsirex** [comment]
There are few issues I'm facing with runit (especially in docker):
https://github.com/hw-cookbooks/runit/issues/100
https://github.com/hw-cookbooks/runit/issues/60 (https://github.com/hw-cookbooks/runit/issues/60#issuecomment-118453623)

Currently, I'm searching for way to fix such issues somehow..

**Comment by jbagel2** [comment]
I'm having similar, but I'm pretty sure its because we are now on Centos7 with now uses systemd.. so we don't really need runit.

**Comment by jsirex** [comment]
@jbagel2 , cookbook has been specially divided into parts for your case: wrap it, but not use default recipe. Use user, install, configure, and your custom service_whatever recipe.
