### ISSUE TITLE
Kibana 4.0.0 Release expects quoted string for elasticsearch value

### ISSUE THREAD

**Issue by rhass-r7** [jsirex/simple-kibana-cookbook#2]
Technically, this is a bug in Kibana 4.0.0 -- but its hopefully quicker and easier to fix in this cookbook.

It seems with the 4.0.0 release, they expect elasticsearch value to be quoted. I have attempted to work around this by setting my attribute to have escaped quotes within the value, but Ruby's YAML generator renders the value as `"'http://mycluster:9200'"` instead of `'http://mycluster:9200'`

**Comment by jsirex** [comment]
will try to fix it on next week.

**Comment by jsirex** [comment]
There are few updates in configuration file. 
bundledPluginIds renamed to bundled_plugin_ids,
elasticsearch renamed to elasticsearch_url.

For quick fix you can override these values in wrapper cookbook. Will create hotfix for that and test

**Comment by jsirex** [comment]
Fixed in 8a1f932e2151db4e20fcfdca802356aba3dbe073
Tagged as v0.2.0, published to supermarket https://supermarket.chef.io/cookbooks/simple-kibana
