### ISSUE TITLE
use node kibana version attribute in download url

### ISSUE THREAD

**Issue by vkhatri** [jsirex/simple-kibana-cookbook#5]
kibana download_url must use node kibana version attribute

**Comment by jsirex** [comment]
This change leads to bug when using wrapper cookbook. `download_url` will be wrong.

It is really bad idea to calculate attributes in such way, isn't?

**Comment by vkhatri** [comment]
@jsirex it should not be and i think if we modify the `version` attribute in a role or wrapper cookbook we would not need to set  `download_url`

**Comment by vkhatri** [comment]
if wrapper cookbook set a different download location, then its up to the user whether the user wants to use version attribute or not.

**Comment by jsirex** [comment]
There is branch `version_test` for you. Check it.

I've overrode version in wrapper cookbook (simple-kibana-test) to `5.5.5`.
Expected calculated resource to be `version now: 5.5.5`, but you'll get:

``` bash
rspec spec/version_spec.rb 

simple-kibana-test::default
[2015-06-08T14:06:32+03:00] WARN: version now: 4.0.2
  expect calculated version right
```

**Comment by jsirex** [comment]
If you need some explanations:

You code literally means:

``` ruby
default['kibana']['version'] = '4.0.2'
default['kibana']['download_url'] = "https://download.elasticsearch.org/kibana/kibana/kibana-#{node['kibana']['version']}-linux-x64.tar.gz"
default['kibana']['version'] = '5.5.5'
```

So it will be impossible to override url in wrapper cookbook.

But, looks like if you set node attributes explicitly via node object/environment/role with higher precedence it will work for you. May be these attributes loads right before cookbooks attributes evaluations. Not sure

**Comment by vkhatri** [comment]
@jsirex i think precedence for node/environment/role is the expected flow to override default. i have not seen any issue with that. but it may be just me, i try to ignore updating default attribute in wrapper cookbook especially when other attributes are evaluated by them.

but i could be wrong, it is really comes down to how the precedence is followed in different scenarios.

**Comment by jsirex** [comment]
Similar issue faced long time ago in elasticsearch cookbook: https://github.com/elastic/cookbook-elasticsearch/issues/178

So, I close it.
