### ISSUE TITLE
init sysv support

### ISSUE THREAD

**Issue by vkhatri** [jsirex/simple-kibana-cookbook#9]
we are using init sysv in our infra and do not have any plan to use runit as such.

will submit a PR if you are ok with making service type configurable by user and adding init sysv support to this cookbook.

**Comment by jsirex** [comment]
This cookbook is designed to be wrapped by yours project cookbook.
In this way you don't need to include `simple-kibana::default` recipe.

Do something like this in yours default recipe:

``` ruby
include_recipe 'simple-kibana::install'
include_recipe 'simple-kibana::configure'
include_recipe 'mywrapper-kibana::service_sysv'
...
```

**Comment by jsirex** [comment]
I'm trying to keep this cookbook as light-weight as possible. Not sure about supporting some/all init services here.

**Comment by vkhatri** [comment]
@jsirex thanks! i will do that. but, i am sure there are lots of folks out there who still relies on `sysv` model.

**Comment by jsirex** [comment]
May be, it will be good point to create such recipe in this cookbook and make it optional:
you're free to include `yourcookbook::your_sysv` or `simple-kibana::service_sysv`

**Comment by vkhatri** [comment]
@jsirex sure!
